spring.datasource.url=${DEV_DB_URL:jdbc:mysql://localhost:3306/gym_crm_dev?createDatabaseIfNotExist=true}
spring.datasource.username=${DEV_DB_USERNAME:root}
spring.datasource.password=${DEV_DB_PASSWORD:12345678}

management.endpoint.health.show-details=always
