spring.application.name=Gym CRM system
spring.profiles.default=local

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [tx:%X{transactionId:-}] %logger{36} - %msg%n

management.endpoints.web.exposure.include=health,metrics,prometheus

security.jwt.expiration-seconds=${JWT_EXPIRATION_SECONDS:3600}
